services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: kyc-celery-tasks-queue
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kyc-celery-result-backend
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: kyc-fastapi-service
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=docker
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./app/main.py:/app/app/main.py
      - ./app/app_config.py:/app/app/app_config.py
      - ./app/api:/app/app/api/
      - ./app/services:/app/app/services/
      - ./app/utils:/app/app/utils/
      - ./temp/frames:/app/temp/frames
      - ./temp/videos:/app/temp/videos
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: kyc-celery-worker
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=docker
      - CELERY_BROKER_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./celery:/app/celery
      - ./app/services:/app/app/services
      - ./app/utils:/app/app/utils
      - ./app/app_config.py:/app/app/app_config.py
      - ./temp/frames:/app/temp/frames
      - ./temp/videos:/app/temp/videos
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq-data:
  redis-data: