FROM python:3.12.2

COPY requirements_celery.txt /requirements_celery.txt
RUN pip install -r /requirements_celery.txt

WORKDIR /celery

COPY ./celery /celery
COPY ./app/services /app/services
COPY ./app/utils /app/utils
COPY ./app/app_config.py /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

RUN touch /celery/__init__.py && \
    touch /app/__init__.py && \
    touch /app/services/__init__.py && \
    touch /app/utils/__init__.py

RUN mkdir -p /app/temp/frames /app/temp/videos

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info"]