FROM python:3.12.2

COPY requirements_app.txt /requirements_celery.txt
RUN pip install -r /requirements_celery.txt

WORKDIR /app

COPY ./celery /app/celery
COPY ./app/services /app/app/services
COPY ./app/utils /app/app/utils
COPY ./app/app_config.py /app/app/

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

RUN touch /app/celery/__init__.py && \
    touch /app/app/__init__.py && \
    touch /app/app/services/__init__.py && \
    touch /app/app/utils/__init__.py

RUN mkdir -p /app/temp/frames /app/temp/videos

CMD ["celery", "-A", "app.celery.celery_app", "worker", "--loglevel=info"]